### ISSUE TITLE
Production logging is insufficient

### ISSUE THREAD

**Issue by jakebloom** [jake-waratahs/murder#3]
At the moment we just have a dev level logging, we will need to upgrade this to a proper production logging method, with IP addresses and such.

**Comment by nickw444** [comment]
Won't nginx access logs be sufficient?

**Comment by jakebloom** [comment]
I also want a "tale of the tape" thing that logs who kills who when. Although it might be just as useful to have that on the front page.

**Comment by johnwiseheart** [comment]
Who kills who would be awesome to have on the front page. Long term goal could also be some kind of API (RSS feed?), such that you could put a feed onto a dashboard or something
